
# _config.yml
title: ikideniz
email: union2030@proton.me
description: İki denizin birleştiği yerde Güncel blog yazıları
baseurl: ""
url: "https://ikidenizz.github.io"
twitter_username: EaPbyai
github_username:  isunion99
image: "/images/describing.jpg"

# URL yapısı
permalink: /:title/



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/isunion99" }
    - { platform: twitter, user_url: "https://twitter.com/EaPbyai" }


header_pages:
  - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
