
markdown: commonmark
title: ikideniz
email: union2030@proton.me
description: Güncel blog yazıları

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ikidenizz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EaPbyai
github_username:  isunion99
image: "/images/describing.jpg"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
