
# Site Bilgileri

# _config.yml
title: ikideniz
description: İki denizin birleştiği yerde Güncel blog yazıları
url: "https://ikidenizz.github.io"
author: "isunion99"
email: union2030@proton.me
baseurl: ""


twitter_username: EaPbyai
github_username:  isunion99
image: "/images/describing.jpg"

# URL yapısı
permalink: /:title/
sass:
  style: compressed # CSS sıkıştırma stilini seçin (compressed, expanded, etc.)

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/isunion99" }
    - { platform: twitter, user_url: "https://twitter.com/EaPbyai" }


header_pages:
  - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # Dil Ayarları
lang: tr
languages:
  en: English
  tr: Türkçe

google_analytics: "G-XXXXXXXXXX"
google_tag_manager: "GTM-XXXXXXX"



# Doğrulama Tokenları
google_site_verification: "token"
bing_site_verification: "token"
yandex_verification: "token"
baidu_verification: "token"
naver_verification: "token"

# Dil Ayarları
languages: ["tr", "en", "de"]