
markdown: kramdown
title: ikideniz
email: union2030@proton.me
description: Güncel blog yazıları

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ikidenizz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EaPbyai
github_username:  isunion99
image: "/images/describing.jpg"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


