
# Site Bilgileri

# _config.yml
title: ikideniz blog
description: İki denizin birleştiği yerde Güneşin altında Güncel blog yazıları
url: https://ikidenizz.github.io
author: isunion99
email: union2030@proton.me
phone: +90123456789
baseurl:
location: Istanbul, Turkey

twitter_username: EaPbyai
github_username:  isunion99
image: /images/describing.jpg

# URL yapısı
permalink: /:title/
sass:
  style: compressed # CSS sıkıştırma stilini seçin (compressed, expanded, etc.)

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


twitter_username: EaPbyai
github_username: isunion99

header_pages:
  - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # Dil Ayarları
lang: tr
languages:
  en: English
  tr: Türkçe



languages: [tr, en, de]
